CREATE DATABASE [educação] ON  PRIMARY 
( NAME = N'educação', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\educação.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'educação_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\educação_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AI
GO
ALTER DATABASE [educação] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [educação] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [educação] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [educação] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [educação] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [educação] SET ARITHABORT OFF 
GO
ALTER DATABASE [educação] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [educação] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [educação] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [educação] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [educação] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [educação] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [educação] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [educação] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [educação] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [educação] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [educação] SET  DISABLE_BROKER 
GO
ALTER DATABASE [educação] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [educação] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [educação] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [educação] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [educação] SET  READ_WRITE 
GO
ALTER DATABASE [educação] SET RECOVERY FULL 
GO
ALTER DATABASE [educação] SET  MULTI_USER 
GO
ALTER DATABASE [educação] SET PAGE_VERIFY CHECKSUM  
GO
USE [educação]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [educação] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
